### ISSUE TITLE
add "Ballot Card Not Found" UI button to county/audit page

### ISSUE THREAD

**Issue by kiniry** [FreeAndFair/ColoradoRLA#326] opened 2017-08-17 20:55 UTC
The button should be directly under, but in the same box as, the instructions "Record here the voter intent...". It should be its own paragraph.  It should read:

```If the ballot card corresponding to the above Ballot ID, Ballot Style, and Imprinted ID cannot be found, select the "Ballot Card Not Found" button and you will be given a new ballot card to audit.```

The appropriate server endpoint to use for this callback is `/ballot-not-found` which contains a ballot id in its body.  See https://github.com/FreeAndFair/ColoradoRLA/blob/master/server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/BallotNotFound.java

In this circumstance the ballot card in question is recorded as a PHANTOM_BALLOT and the risk limit is updated appropriately.

**Comment by ranweiler** [comment] 2017-08-18 02:50
This is all but done. We can test after @dmzimmerman changes the endpoint to `POST`, and slightly modifies the expected request body (from a flat `<number>` to `{ id: <number> }`).

**Comment by nealmcb** [comment] 2017-08-22 04:13
In testing this endpoint as a POST with smoketest, it returns a 200, but `estimated_ballots_to_audit:` doesn't increase. It decreases instead.

**Comment by ranweiler** [comment] 2017-08-22 21:33
This is done and integrated. I'm going to close this issue out, because it is about the client. @nealmcb, could you please open a new issue for the remaining server part of this, including expected behavior?

**Closed by ranweiler** 2017-08-22 21:33 UTC
Labels: client, feature, ui/ux
