### ISSUE TITLE
End of all Audit Rounds page

### ISSUE THREAD

**Issue by sfsinger19103** [FreeAndFair/ColoradoRLA#635] opened 2017-09-01 21:41 UTC
CDOS writes: "We suspect that the form referenced below is the Audit Board certification described on page 8 of the Audit Board Reporting Utility Mockup.docx file" 

However, F&F intent was that this page should allow the County user to pull the final audit report, not an end-of-round certification.

Resolve!

**Comment by sfsinger19103** [comment] 2017-09-05 01:18
Asked in SS email to CDOS 9/1: 

> The Audit Board Utility Mockup document Dwight sent specifies and end-of-round page for the audit board. Would you like to specify an end-of-audit page for the County? That was the intent of the "End of All Audit Rounds" page in your item #14.

**Comment by sfsinger19103** [comment] 2017-09-12 00:56
CDOS 9/11:
No. We have discussed this situation again, and decided that since the audit judges are signing off on every round and we are able to pull a report that displays, by county, which ballots were pulled in each round and their audited disposition, we don’t need the additional certification sign off sheet/end of round on the “End of All Audit Rounds” page.

**Comment by ranweiler** [comment] 2017-09-12 20:01
Looks like this is a duplicate of #480.

**Comment by ranweiler** [comment] 2017-09-12 20:03
Closing, since it is a dupe.

**Closed by ranweiler** 2017-09-12 20:03 UTC
Labels: CDOS Priority, duplicate, ui/ux
