### ISSUE TITLE
permitted to start an audit without an audit board

### ISSUE THREAD

**Issue by kiniry** [FreeAndFair/ColoradoRLA#471] opened 2017-08-25 08:04 UTC
If the SOS has started the audit, I am permitted to start the audit in the County Dashboard even though I have not yet signed in an Audit Board.

**Comment by dmzimmerman** [comment] 2017-08-25 15:28
On the server side this is a duplicate of #467

**Comment by ranweiler** [comment] 2017-08-26 22:04
I can no longer repro this client side as of #468. I captured the specific need for more user feedback in this cases in #494.

**Closed by ranweiler** 2017-08-26 22:04 UTC
Labels: bug, client, server
